version: '3.8'

services:
  ai-creative-partner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    environment:
      - MODEL_NAME=TheBloke/Llama-2-7B-Chat-GGUF
      - DEVICE=cpu
      - TEXT_TO_IMAGE_APP_ID=f0997a01-d6d3-a5fe-53d8-561300318557
      - IMAGE_TO_3D_APP_ID=69543f29-4d41-4afc-7f29-3d51591f11eb
    # Keep container running even if the process exits
    tty: true
    stdin_open: true